# -*- coding: utf-8 -*-
"""FLAM Assesment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqfcwcy3EzV248VQz2YESo-mDOdZ6eb4
"""

import numpy as np
import pandas as pd
from scipy.optimize import minimize

# Load data (assuming xy_data.csv is in same directory)
data = pd.read_csv('xy_data.csv')
x_data = data['x'].values
y_data = data['y'].values

def parametric_curve(t, theta, M, X):
    """Parametric curve equations"""
    exp_term = np.exp(M * np.abs(t)) * np.sin(0.3 * t)
    x = t * np.cos(theta) - exp_term * np.sin(theta) + X
    y = 42 + t * np.sin(theta) + exp_term * np.cos(theta)
    return x, y

def estimate_t_values(x_data, y_data):
    """Estimate t values using arc length parameterization"""
    points = np.column_stack([x_data, y_data])
    distances = np.linalg.norm(np.diff(points, axis=0), axis=1)
    cumulative_length = np.concatenate([[0], np.cumsum(distances)])
    t_est = 6 + (cumulative_length / cumulative_length[-1]) * 54
    return t_est

def objective(params, t_est, x_data, y_data):
    """Objective function for optimization"""
    theta, M, X = params
    x_pred, y_pred = parametric_curve(t_est, theta, M, X)
    return np.sum((x_data - x_pred)**2 + (y_data - y_pred)**2)

print("FLAM Parameter Estimation")
print("=" * 40)

t_estimated = estimate_t_values(x_data, y_data)
print(f"Estimated t-range: {t_estimated[0]:.2f} to {t_estimated[-1]:.2f}")

initial_guess = [0.7, 0.02, 50]
bounds = [(0.1, 0.87), (-0.049, 0.049), (1, 99)]

print("\nOptimizing parameters...")
result = minimize(objective, initial_guess, args=(t_estimated, x_data, y_data),
                 bounds=bounds, method='L-BFGS-B')

theta_opt, M_opt, X_opt = result.x

print("\n" + "=" * 40)
print("OPTIMIZATION RESULTS:")
print("=" * 40)
print(f"θ (theta)  = {theta_opt:.6f} radians")
print(f"           = {np.degrees(theta_opt):.2f}°")
print(f"M          = {M_opt:.6f}")
print(f"X          = {X_opt:.6f}")
print(f"Success    = {result.success}")
print(f"Final loss = {result.fun:.6f}")
print(f"Iterations = {result.nit}")

x_pred, y_pred = parametric_curve(t_estimated, theta_opt, M_opt, X_opt)
rmse = np.sqrt(np.mean((x_data - x_pred)**2 + (y_data - y_pred)**2))
print(f"RMSE       = {rmse:.6f}")
print("\nCONSTRAINT VERIFICATION:")
print("=" * 40)
print(f"θ in (0, 0.8727): {0 < theta_opt < 0.8727}")
print(f"M in (-0.05, 0.05): {-0.05 < M_opt < 0.05}")
print(f"X in (0, 100): {0 < X_opt < 100}")
print("\nFINAL PARAMETRIC EQUATION:")
print("=" * 40)
print(f"x(t) = t·cos({theta_opt:.4f}) - e^({M_opt:.4f}|t|)·sin(0.3t)·sin({theta_opt:.4f}) + {X_opt:.4f}")
print(f"y(t) = 42 + t·sin({theta_opt:.4f}) + e^({M_opt:.4f}|t|)·sin(0.3t)·cos({theta_opt:.4f})")

